import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { HeaderApp } from "@/components/layout";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        <HeaderApp />
        <main className="max-w-screen-xl m-auto">{children}</main>
      </body>
    </html>
  );
}
